version: 1.0.{build}
image: Visual Studio 2015
configuration: Debug
before_build:
  - nuget restore
build:
  project: .\XTenLib.sln
  verbosity: minimal
test:
  assemblies:
    only:
      - XTenLib.Tests/bin/Debug/XTenLib.Tests.dll
after_test:
  - ps: .\XTenLib\nuget_pack.ps1
artifacts:
  - path: .\XTenLib\bin\Debug\XTenLib.dll
    name: XTenLib
    type: File
  - path: '*.nupkg'
    name: XTenLib nupkg
    type: NuGetPackage
deploy:
  - provider: GitHub
    auth_token:
      secure:  1aMBEFi1qBAoV4H+LYx7hoVLgXJfndGoQ8I8qjLsoxXNA1zS+zgQHi2zVlRrmw1v
    draft: false
    prerelease: false    
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: nFeqkA4BfbPz0Fpqo0Q5+/Y1ISiQ/lGEj3oqH07+XUo9S3FrixM0ENcd2hj3UARu
    skip_symbols: false
    artifact: /.*\.nupkg/
    on:
      appveyor_repo_tag: true

